### ISSUE TITLE
Fixing Styling and Adding criteria for new subjects

### ISSUE THREAD

**Issue by Pranav-JJ** [Open-Source-Chandigarh/Attendance-Manager#22]
I see a few styling and spelling errors in the website.

![image](https://github.com/Open-Source-Chandigarh/Attendance-Manager/assets/109146414/c663704f-796e-4985-a2d0-28af3dd86cc6)

In this the issue is that you can scroll right, for no added content.

![image](https://github.com/Open-Source-Chandigarh/Attendance-Manager/assets/109146414/8b9765cd-bc31-4e49-91c4-2577a52da36e)
![image](https://github.com/Open-Source-Chandigarh/Attendance-Manager/assets/109146414/e2da9370-8593-45b4-8f4e-ef78c324c076)
 
 Minor spelling errors.

I wish to fix these issues.

At the same time I also wish to add a criteria of Subject teacher for each new subject as well.
So, if possible can you assign me this issue as a part of HacktoberFest?

**Comment by hollermay** [comment]
Go for it
