### ISSUE TITLE
minor overlapping and oversizing issue

### ISSUE THREAD

**Issue by pabitra-kumar** [Open-Source-Chandigarh/Attendance-Manager#23]
Hey, I want to fix the following issues.

1. overlapping of About animation to navbar

![image](https://github.com/Open-Source-Chandigarh/Attendance-Manager/assets/98006358/6a3e3d95-fb5f-48ee-8124-6596d99a36b7)

2.  website width is greater than the screen size
![image](https://github.com/Open-Source-Chandigarh/Attendance-Manager/assets/98006358/47c641a2-6af5-4158-b6e7-f8d9e8b61e61)

3. Structuring of Attendance.json file

**Comment by hollermay** [comment]
Go for it :)
