### ISSUE TITLE
Bug: in add a new subject if user doesn't enter anything it should ask the user to enter details

### ISSUE THREAD

**Issue by shreyamaurya029** [Open-Source-Chandigarh/Attendance-Manager#9]
basically when i don't enter anything it should ask the user to enter details, currently its taking us to a new page where everything is undefined

**Comment by hollermay** [comment]
we'll be glad for this contribution :)

**Comment by hollermay** [comment]
@shreyamaurya029 any leads?

**Comment by shreyamaurya029** [comment]
i am working on it
